config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root "dashboard#index"
  post "/", to: "dashboard#select"
  resources :pizzas, :toppings, except: [ :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  has_and_belongs_to_many :toppings

  validates :name, uniqueness: { case_sensitive: false }
  validate :unique_toppings_combination

  def is_vegetarian
    toppings.all?(&:vegetarian) && vegetarian
  end

  def numeric_total(attribute)
    sum = self[attribute]
    if !sum.is_a? Numeric
      return nil
    end
    toppings.each do |topping|
      sum += topping[attribute]
    end
    sum
  end

  private

  def unique_toppings_combination
    # TODO: Find more performant implementation
    # TODO: Update to also make sure pizzas have same vegetarian, calories, price
    Pizza.where.not(id: id).each do |pizza|
      if pizza.toppings.sort == toppings.sort
        errors.add(:toppings, "are a combination already in use by the pizza #{pizza.name}")
      end
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users

  STORE_OWNER = "Store Owner"
  CHEF = "Chef"
end

app/models/topping.rb
class Topping < ApplicationRecord
  has_and_belongs_to_many :pizzas

  validates :name, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :roles

  def has_role(role_name)
    roles.where(name: role_name).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :current_user

  def user_from_session
    User.find_by(id: session[:user_id])
  end

  def current_user
    @current_user = user_from_session()
  end

  def authorize_store_owner
    if not user_from_session()&.has_role(Role::STORE_OWNER)
      flash[:error] = "Only store owners may access that page"
      redirect_to :root
    end
  end

  def authorize_chef
    if not user_from_session()&.has_role(Role::CHEF)
      flash[:error] = "Only chefs may access that page"
      redirect_to :root
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @users = User.all()
  end

  def select
    session[:user_id] = selected_user_params
    flash[:notice] = "Now 'logged in' as the user #{user_from_session()&.name}"
    redirect_to :root
  end

  private
    def selected_user_params
      params.require(:user_id)
    end
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :authorize_chef

  def index
    @pizzas = Pizza.all
  end

  def new
    @pizza = Pizza.new()
    @toppings = Topping.all
  end

  def create
    @pizza = Pizza.new(pizza_params)
    if @pizza.save
      flash[:notice] = "Sucessfully created pizza #{@pizza.name}"
      redirect_to pizzas_path
    else
      flash[:error] = "There was an issue creating the pizza: #{@pizza.errors.full_messages}"
      @toppings = Topping.all
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @pizza = Pizza.find(params[:id])
    @toppings = Topping.all
  end

  def update
    @pizza = Pizza.find(params[:id])
    if @pizza.update(pizza_params)
      flash[:notice] = "Sucessfully updated pizza #{@pizza.name}"
      redirect_to pizzas_path
    else
      flash[:error] = "There was an issue updating the pizza: #{@pizza.errors.full_messages}"
      @toppings = Topping.all
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @pizza = Pizza.find(params[:id])
    @pizza.destroy()
    flash[:notice] = "Pizza deleted"
    redirect_to pizzas_path
  end

  private
    def pizza_params
      params.require(:pizza).permit(:name, :vegetarian, :price, :calories, topping_ids: [])
    end
end

app/controllers/toppings_controller.rb
class ToppingsController < ApplicationController
  before_action :authorize_store_owner

  def index
    @toppings = Topping.all
  end

  def new
    @topping = Topping.new()
  end

  def create
    @topping = Topping.new(topping_params)
    if @topping.save
      flash[:notice] = "Sucessfully created topping #{@topping.name}"
      redirect_to toppings_path
    else
      flash[:error] = "There was an issue creating the topping: #{@topping.errors.full_messages}"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @topping = Topping.find(params[:id])
  end

  def update
    @topping = Topping.find(params[:id])
    if @topping.update(topping_params)
      flash[:notice] = "Sucessfully updated topping #{@topping.name}"
      redirect_to toppings_path
    else
      flash[:error] = "There was an issue updating the topping: #{@topping.errors.full_messages}"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @topping = Topping.find(params[:id])
    @topping.destroy()
    flash[:notice] = "Topping deleted"
    redirect_to toppings_path
  end

  private
    def topping_params
      params.require(:topping).permit(:name, :vegetarian, :price, :calories)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/_user_row.html.erb
<tr>
	<td><%= user_row.name %></td>
	<td><%= user_row.has_role(Role::STORE_OWNER) %></td>
	<td><%= user_row.has_role(Role::CHEF) %></td>
	<td>
		<%= button_to "Select", root_path(user_row), method: :post, params: {user_id: user_row} %>
	</td>
</tr>

app/views/dashboard/index.html.erb
<h1>Test Dashboard</h1>
<% if @current_user %>
	<% if @current_user.has_role(Role::STORE_OWNER) %>
		<div><%= link_to "Manage toppings", toppings_path, class: "button" %></div>
	<% end %>
	<% if @current_user.has_role(Role::CHEF) %>
		<div><%= link_to "Manage pizzas", pizzas_path, class: "button" %></div>
	<% end %>
<% else %>
	<div>Select a user to test the application</div>
<% end %>
<table>
	<thead>
	  <tr>
	    <th>Name</th>
	    <th>Store Owner</th>
	    <th>Chef</th>
	  </tr>
	</thead>
	<tbody>
	  <%= render partial: "user_row", collection: @users %>
	</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Pizza Manager" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "https://cdn.simplecss.org/simple.min.css" %>
    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <% flash.each do |key, message| %>
      <div><%= message %></div>
    <% end %>
    <% if @current_user %>
      <div><%= link_to "Dashboard", root_path, class: "button" %> <div>Using user <%= @current_user.name %></div></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pizzas/_pizza_form.html.erb
<%= form_with model: @pizza do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :vegetarian %>
    <%= form.check_box :vegetarian %>
  </div>

	<div>
    <%= form.label :price %>
    <%= form.number_field :price, in: 0..20.0, step: 1 %>
  </div>

	<div>
    <%= form.label :calories %>
    <%= form.number_field :calories, in: 0..1000, step: 10 %>
  </div>

	<div>
    <%= form.label :toppings %>
    <%= form.collection_check_boxes :topping_ids, @toppings, :id, :name %>
  </div>

  <div>
    <%= form.submit %>
    <%= link_to "Cancel", pizzas_path, class: "button" %>
  </div>
<% end %>

app/views/pizzas/_pizza_row.html.erb
<tr>
	<td><%= pizza_row.name %></td>
	<td><%= pizza_row.vegetarian %></td>
	<td><%= pizza_row.price %></td>
	<td><%= pizza_row.calories %></td>
	<td>
		<%= link_to "Edit", edit_pizza_path(pizza_row.id), class: "button" %>
		<!-- TODO: Add actual confirm to delete button -->
		<%= button_to "Delete", pizza_row, method: :delete %>
	</td>
</tr>
<%= render partial: "toppings/topping_row", collection: pizza_row.toppings %>
<tr>
	<td class="emtpy-cell"/>
	<td><%= pizza_row.is_vegetarian() %></td>
	<td><%= pizza_row.numeric_total("price") %></td>
	<td><%= pizza_row.numeric_total("calories") %></td>
</tr>

app/views/pizzas/edit.html.erb
<h1>Edit pizza</h1>
<%= render partial: "pizza_form", object: @pizza %>

app/views/pizzas/index.html.erb
<h1>Pizzas</h1>
<div><%= link_to "New pizza", new_pizza_path, class: "button" %></div>
<table>
	<thead>
	  <tr>
	    <th>Name</th>
	    <th>Vegetarian</th>
	    <th>Price</th>
	    <th>Calories</th>
			<th>Actions</th>
	  </tr>
	</thead>
	<tbody>
	  <%= render partial: "pizza_row", collection: @pizzas %>
	</tbody>
</table>

app/views/pizzas/new.html.erb
<h1>New pizza</h1>
<%= render partial: "pizza_form", object: @pizza %>

app/views/toppings/_topping_form.html.erb
<%= form_with model: @topping do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

	<div>
    <%= form.label :vegetarian %>
    <%= form.check_box :vegetarian %>
  </div>

	<div>
    <%= form.label :price %>
    <%= form.number_field :price, in: 0..20.0, step: 1 %>
  </div>

	<div>
    <%= form.label :calories %>
    <%= form.number_field :calories, in: 0..1000, step: 10 %>
  </div>

  <div>
    <%= form.submit %>
    <%= link_to "Cancel", toppings_path, class: "button" %>
  </div>
<% end %>

app/views/toppings/_topping_row.html.erb
<tr>
	<td><%= topping_row.name %></td>
	<td><%= topping_row.vegetarian %></td>
	<td><%= topping_row.price %></td>
	<td><%= topping_row.calories %></td>
	<% if @current_user.has_role(Role::STORE_OWNER) %>
		<td>
			<%= link_to "Edit", edit_topping_path(topping_row.id), class: "button" %>
			<!-- TODO: Add actual confirm to delete button -->
			<%= button_to "Delete", topping_row, method: :delete %>
		</td>
	<% end %>
</tr>

app/views/toppings/edit.html.erb
<h1>Edit topping</h1>
<%= render partial: "topping_form", object: @topping %>

app/views/toppings/index.html.erb
<h1>Toppings</h1>
<div><%= link_to "New topping", new_topping_path, class: "button" %></div>
<table>
	<thead>
	  <tr>
	    <th>Name</th>
	    <th>Vegetarian</th>
	    <th>Price</th>
	    <th>Calories</th>
			<th>Actions</th>
	  </tr>
	</thead>
	<tbody>
	  <%= render partial: "topping_row", collection: @toppings %>
	</tbody>
</table>

app/views/toppings/new.html.erb
<h1>New topping</h1>
<%= render partial: "topping_form", object: @topping %>